name: Blue Preprocessor Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Preprocess:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
          audience: sts.amazonaws.com
          role-session-name: GitHubActionsSession

      - name: Get changed package folders
        run: |
          # Get the base and head commits of the PR
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)

          # Extract unique root folders, excluding .github and files in root
          echo "$CHANGED_FILES" | while read -r FILE; do
            if [[ "$FILE" =~ ^\.github/ ]] || [[ ! "$FILE" =~ "/" ]]; then
              continue
            fi
            
            # Get the root folder
            ROOT_FOLDER=$(echo "$FILE" | cut -d'/' -f1)
            echo "$ROOT_FOLDER"
          done | sort -u > changed_packages.txt

          # Print the results
          echo "Changed package folders:"
          cat changed_packages.txt

          # Set output for next steps
          if [ -s changed_packages.txt ]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Download blue-preprocessor.jar
        run: |
          aws s3 cp "s3://${{ vars.S3_BUCKET_NAME }}/scripts/blue-preprocessor.jar" ./.github/scripts

      # Updated to Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17" # Changed from 11 to 17

      - name: Set execute permissions for JAR
        run: chmod +x .github/scripts/blue-preprocessor.jar

      - name: Run Blue Preprocessor
        run: |
          java -jar ./.github/scripts/blue-preprocessor.jar ./ ./blue-preprocessed

      - name: Copy changed_packages.txt to artifacts
        if: env.CHANGES_DETECTED == 'true'
        run: |
          cp changed_packages.txt ./blue-preprocessed/

      - name: Upload preprocessed files
        uses: actions/upload-artifact@v4
        with:
          name: blue-preprocessed
          path: ./blue-preprocessed
          retention-days: 5

  UploadPackages:
    needs: Preprocess
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Download preprocessed files
        uses: actions/download-artifact@v4
        with:
          name: blue-preprocessed
          path: ./blue-preprocessed

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Process and upload files
        run: |
          # Read the changed packages
          if [ ! -f "./blue-preprocessed/changed_packages.txt" ]; then
            echo "No changed packages file found"
            exit 0
          fi

          # Read blue IDs into associative array
          declare -A BLUE_IDS
          while IFS=": " read -r package id; do
            BLUE_IDS["$package"]="$id"
          done < <(yq eval-all '.[] | to_entries | .[] | .key + ": " + .value' ./blue-preprocessed/blue-ids.yaml)

          # Process each changed package
          while IFS= read -r package; do
            # Skip empty lines
            [ -z "$package" ] && continue
            
            echo "Processing package: $package"
            
            # Get blueId for the package
            blueId="${BLUE_IDS[$package]}"
            if [ -z "$blueId" ]; then
              echo "Warning: No blueId found for package $package"
              continue
            fi

            # Process all yaml and blue files in the package directory
            for file in ./blue-preprocessed/"$package"/*.[yb][al][mu][el]*; do
              [ -f "$file" ] || continue
              
              filename=$(basename "$file")
              filename_without_ext="${filename%.*}"
              
              # Convert YAML to JSON
              json_content=$(yq eval -o=json "$file")
              
              # Upload to S3
              echo "$json_content" | aws s3 cp - "s3://${{ vars.S3_BUCKET_NAME }}/packages/$package/$blueId/${filename_without_ext}.json"
              
              echo "Uploaded $filename to s3://${{ vars.S3_BUCKET_NAME }}/packages/$package/$blueId/${filename_without_ext}.json"
            done
          done < "./blue-preprocessed/changed_packages.txt"

  TriggerSDKs:
    needs: Preprocess
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blue-repository-js
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/bluecontract/blue-repository-js/dispatches \
            -d '{"event_type":"blue-preprocessor-completed","client_payload":{"run_id":"${{ github.run_id }}"}}'
