name: Blue Preprocessor Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        type: string

jobs:
  preprocess:
    runs-on: ubuntu-latest
    
    steps:
      # First, checkout LFS files
      - name: Checkout LFS objects
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true
          fetch-depth: 0  # Fetch all history

      # Explicitly pull LFS files
      - name: Fetch LFS files
        run: git lfs fetch --all && git lfs checkout

      # Verify the JAR file exists and check its size
      - name: Verify JAR file
        run: |
          ls -l .github/scripts/blue-preprocessor.jar
          file .github/scripts/blue-preprocessor.jar

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Set execute permissions for JAR
        run: chmod +x .github/scripts/blue-preprocessor.jar
      
      - name: Run Blue Preprocessor
        run: |
          java -jar ./.github/scripts/blue-preprocessor.jar ./ ./blue-preprocessed
      
      - name: Upload preprocessed files
        uses: actions/upload-artifact@v4
        with:
          name: blue-preprocessed-files
          path: ./blue-preprocessed
          retention-days: 5