name: Prevent Version Modifications

on:
  pull_request:
    branches:
      - test
    paths:
      - 'types/**'

jobs:
  check_modifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for modifications in version folders
        run: |
          # Get the base branch commit
          BASE_COMMIT=${{ github.event.pull_request.base.sha }}
          
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-status $BASE_COMMIT HEAD)
          
          # Function to check if path is a new directory
          is_new_directory() {
            local path=$1
            if ! git ls-tree $BASE_COMMIT "$path" > /dev/null 2>&1; then
              return 0  # True, it's a new directory
            fi
            return 1  # False, directory already exists
          }
          
          # Process each changed file
          echo "$CHANGED_FILES" | while read -r line; do
            # Split the line into status and file path
            STATUS=$(echo "$line" | cut -f1)
            FILE=$(echo "$line" | cut -f2)
            
            # Skip if not in types directory
            if [[ ! "$FILE" =~ ^types/ ]]; then
              continue
            fi
            
            # Extract the contract and version path
            if [[ "$FILE" =~ ^types/([^/]+)/([^/]+) ]]; then
              CONTRACT_PATH="types/${BASH_REMATCH[1]}"
              VERSION_PATH="types/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"
              
              # If modifying existing version directory
              if ! is_new_directory "$VERSION_PATH"; then
                echo "❌ Error: Modification detected in existing version directory: $VERSION_PATH"
                echo "Only new version directories can be added."
                exit 1
              fi
              
              # If modifying existing contract directory (but not adding new version)
              if ! is_new_directory "$CONTRACT_PATH" && [[ "$FILE" =~ ^types/[^/]+/$ ]]; then
                echo "❌ Error: Modification detected in existing contract directory: $CONTRACT_PATH"
                echo "Only new contracts or new versions can be added."
                exit 1
              fi
            fi
          done
          
          echo "✅ All changes are valid - only new versions or contracts were added."